version: '3'
services:
  mlnet_webapi:
    image: daxnet/mlnet_webapi
    build:
      context: .
      dockerfile: mlnet_webapi/Dockerfile
    environment:
      - BLOB_ACCOUNT_NAME=${BLOB_ACCOUNT_NAME}
      - BLOB_DEFAULT_ENDPOINTS_PROTOCOL=${BLOB_DEFAULT_ENDPOINTS_PROTOCOL}
      - BLOB_ENDPOINT_SUFFIX=${BLOB_ENDPOINT_SUFFIX}
      - BLOB_ACCOUNT_KEY=${BLOB_ACCOUNT_KEY}
      - Serilog__MinimumLevel=${Serilog__MinimumLevel:-Debug}
    container_name: mlnet_webapi
    ports:
      - 880:80
      - 8443:443
